# need to load LineProperties first
include("structures/LineProperties.jl")
include("structures/SolarData.jl")
include("structures/SpecParams.jl")
include("structures/DiskParams.jl")
include("structures/SynthWorkspace.jl")
include("structures/GPUAllocs.jl")
include("structures/GPUSolarData.jl")
include("structures/Planet.jl")
include("structures/RossiterAllocs.jl")